### ISSUE TITLE
please review https://www.globalbioticinteractions.org/parasitetracker

### ISSUE THREAD

**Issue by jhpoelen** [ParasiteTracker/data-issues-observations-and-questions#3]
hi!

I've created a list of parasite tracker collections + indexed status at:

https://www.globalbioticinteractions.org/parasitetracker

The idea is to use this page to keep track of progress.

**Comment by seltmann** [comment]
Awesome! @zaspelj I can edit this page. Would be a good task to update collection information at the summit.

**Comment by jhpoelen** [comment]
Closing issue. Please open new issues for improvement ideas for GloBI parasite page.

**Comment by seltmann** [comment]
Closing issue. Please open new issues for improvement ideas for GloBI parasite page.
