### ISSUE TITLE
verbatimInteractionName not in indexed-interactions.tsv

### ISSUE THREAD

**Issue by seltmann** [ParasiteTracker/data-issues-observations-and-questions#5]
@jhpoelen Can we add it to the https://www.globalbioticinteractions.org/parasitetracker indexted-interactions.tsv?

**Comment by seltmann** [comment]
It is using elton 0.9.5

--

**Comment by jhpoelen** [comment]
please consider adding a feature request to https://github.com/globalbioticinteractions/elton/issues/

**Comment by seltmann** [comment]
Moved to https://github.com/globalbioticinteractions/elton/issues/35
